/**
 * Plan Templates
 *
 * Templates for generating different types of plan documents.
 */

export interface TemplateContext {
  sessionId: string;
  date: string;
  title?: string;
  [key: string]: unknown;
}

export const Templates = {
  /**
   * Design plan header
   */
  designHeader(ctx: TemplateContext): string {
    return `# ${ctx.title || 'Design Plan'}

**Session:** ${ctx.sessionId}
**Date:** ${ctx.date}
**Status:** Approved

---

`;
  },

  /**
   * Phase plan header
   */
  phaseHeader(ctx: TemplateContext): string {
    return `# Phase Plan

**Session:** ${ctx.sessionId}
**Date:** ${ctx.date}

---

`;
  },

  /**
   * Task plan header
   */
  taskHeader(ctx: TemplateContext): string {
    return `# Task Plan

**Session:** ${ctx.sessionId}
**Date:** ${ctx.date}

> **For Claude:** REQUIRED SUB-SKILL: Use superpowers:executing-plans to implement this plan task-by-task.

---

`;
  },

  /**
   * Phase section
   */
  phase(name: string, description: string, sequence: number): string {
    return `## Phase ${sequence}: ${name}

${description}

`;
  },

  /**
   * Milestone section
   */
  milestone(name: string, description: string, sequence: number): string {
    return `### ${sequence}. ${name}

${description || 'No description provided.'}

`;
  },

  /**
   * Acceptance criteria list
   */
  acceptanceCriteria(criteria: string[]): string {
    if (criteria.length === 0) return '';
    return `**Acceptance Criteria:**
${criteria.map((c) => `- [ ] ${c}`).join('\n')}

`;
  },

  /**
   * Task section
   */
  task(description: string, filePaths: string[], dependencies: string[]): string {
    const lines = [`### Task: ${description}`, ''];

    if (filePaths.length > 0) {
      lines.push('**Files:**');
      lines.push(...filePaths.map((f) => `- \`${f}\``));
      lines.push('');
    }

    if (dependencies.length > 0) {
      lines.push(`**Dependencies:** ${dependencies.join(', ')}`);
      lines.push('');
    }

    return lines.join('\n');
  },

  /**
   * Execution handoff footer
   */
  executionHandoff(sessionId: string): string {
    return `---

## Execution Handoff

Two execution options:

**1. Subagent-Driven (this session)** - I dispatch fresh subagent per task, review between tasks, fast iteration

**2. Parallel Session (separate)** - Open new session in worktree with executing-plans, batch execution with checkpoints

**Session ID:** ${sessionId}
`;
  },

  /**
   * Document footer
   */
  footer(): string {
    return `
---

*Generated by Razorweave Boardroom*
`;
  },
};
